[tool.poetry]
name = "solarel"
version = "0.1.0"
description = ""
authors = ["Charlie Howcroft <ch61@utas.edu.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
